# Spring Properties
spring:
  application:
    name: web-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 8080   # HTTP (Tomcat) port

security:
  oauth2:
    client:
      clientId: 479757998513-vmikq038ocro0br3clg6v6ab4129emda.apps.googleusercontent.com
      clientSecret: bjag5xJH_LqRFjk9SpUsg9ip
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile email
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me


#duobk:
  #superadmins: petrodarchyn@gmail.com, petrodarchyn2@gmail.com, petrodarchyn3@gmail.com

zuul:
  ignoredServices: '*'
  routes:
    constructor-service: /constructor/**
    dictionary-service: /dictionary/**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000000


ribbon:
  ReadTimeout: 60000000
  connection-timeout: 3000
  eureka:
    enabled: true